version: '2'
services:
  hugo:
    #image: jojomi/hugo:latest
    build: ./hugo-dockerfile
    volumes:
      - hugo_src:/src
      - ./output/:/output
    environment:
      #- HUGO_WATCH=true
      - HUGO_REFRESH_TIME=20
      - HUGO_THEME=casper
      - HUGO_BASEURL=http://localhost
      - HUGO_BUILD_DRAFTS=yes
      - WORK_BRANCH=maven-docker
    

  web:
    image: fnichol/uhttpd
    volumes:
      - ./output:/www
    ports:
      - 80:80
    restart: always

volumes:
  hugo_src:
    driver: local
